apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  generators:
  - git:
      repoURL: https://github.com/patelmaulik/gitops
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: santana
      source:
        repoURL: https://github.com/patelmaulik/gitops
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 1h
            maxDuration: 2h
            factor: 2