# Source - https://github.com/patelmaulik/gitops
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: santana
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Device Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  # namespaceResourceBlacklist:
  # - group: ''
  #   kind: ResourceQuota
  # - group: ''
  #   kind: LimitRange
  # - group: ''
  #   kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
  - group: '*'
    kind: "*"
  # - group: 'apps'
  #   kind: Deployment
  # - group: 'apps'
  #   kind: StatefulSet

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  roles:
  # A role which provides admin access to all applications in the project
  - name: admin-access
    description: admin privileges to santana
    policies:
    - p, proj:santana:admin-access, applications, get, santana/*, allow
    groups:
    - santana-admins

  # A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
  # sync privileges to a CI system
  - name: ci-role
    description: Sync privileges for guestbook-dev
    policies:
    - p, proj:santana:ci-role, applications, sync, santana/guestbook-dev, allow

    # NOTE: JWT tokens can only be generated by the API server and the token is not persisted
    # anywhere by Argo CD. It can be prematurely revoked by removing the entry from this list.
    # jwtTokens:
    # - iat: 1535390316
  syncWindows:
  - applications:
    - '*'
    clusters:
    - '*'
    duration: 1h
    kind: allow
    manualSync: true
    namespaces:
    - '*'
    schedule: '* 22 * * *'
    timeZone: Europe/London
