apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: santana
  source:
    path: appset
    repoURL: https://github.com/patelmaulik/gitops
    targetRevision: main
  destination:
    name: ''
    namespace: argo-apps
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 1h
        maxDuration: 2h
        factor: 2
